version: '2'

services:

  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: reverse_proxy/
      dockerfile: Dockerfile    
    depends_on:
      - load-balancer
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy:/var/log/nginx  
    ports:
      - 80:80

  node1:
    container_name: node1
    build:
      context: node1/
      dockerfile: Dockerfile
    depends_on:
      - load-balancer
      
  node2:
    container_name: node2
    build:
      context: node2/
      dockerfile: Dockerfile
    depends_on:
      - load-balancer

  node3:
    container_name: node3
    build:
      context: node3/
      dockerfile: Dockerfile
    depends_on:
      - load-balancer
      
  load-balancer:
    container_name: load-balancer
    build:
      context: load_balancer/
      dockerfile: Dockerfile
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./load_balancer:/var/log/nginx
