version: '2'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
      - nodehost1
      - nodehost2
      - loadb
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  nodehost1:
    container_name: nodehost1
    build:
      context: node1/
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    depends_on:
      - loadb
      
  nodehost2:
    container_name: nodehost2
    build:
      context: node2/
      dockerfile: Dockerfile
    ports:
      - 3001:4001
    depends_on:
      - loadb

  loadb:
    container_name: loadb
    build:
      context: load_balancer/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/workspace/load-balancer/load_balancer:/var/log/nginx
