version: '2'

services:

  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse-proxy
    depends_on:
      - load-balancer
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy:/var/log/nginx  
    ports:
      - 80:80

  nodehost1:
    container_name: nodehost1
    build:
      context: node1/
      dockerfile: Dockerfile
    depends_on:
      - load-balancer
      
  nodehost2:
    container_name: nodehost2
    build:
      context: node2/
      dockerfile: Dockerfile
    depends_on:
      - load-balancer

  load-balancer:
    container_name: load-balancer
    build:
      context: load_balancer/
      dockerfile: Dockerfile
    volumes:
      - ./load_balancer/nginx.conf:/etc/nginx/nginx.conf
      - ./load_balancer:/var/log/nginx
